language: python

python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

env:
  global:
    - DB_HOST=127.0.0.1
    - DB_NAME=flaskProducts
    - DB_USER=flaskProductUser
    - DB_PASSWORD=flaskProductPW

services:
  - postgresql

# commands to run tests
before_script:
  - psql -c 'create database travis_ci_test;' -U flaskProductUser

script:
  - nosetests --with-coverage
  - pytest

after_success:
  - codecov

