language: python

python:
  - "2.7"

services:
  - postgresql

env:
  global:
    - DB_HOST=127.0.0.1
    - DB_NAME=postgres
    - DB_USER=postgres
    - DB_PASSWORD=postgres

# command to install dependencies
install: "pip install -r requirements.txt"

# commands to run tests
before_script:
  - psql -c 'create database flaskProducts;' -U postgres

script:
  - nosetests --with-coverage
  - pytest

after_success:
  - codecov

